# Configuration for onedev setup
# Name of the big-bear-onedev application
version: "3.7"
# Service definitions for the big-bear-onedev application
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-onedev_big-bear-onedev_1
      APP_PORT: "6610"
  # Service name: big-bear-onedev
  # The `big-bear-onedev` service definition
  big-bear-onedev:
    # Image to be used for the container
    image: 1dev/server:14.1.1
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local /DATA/AppData/big-bear-onedev/data directory to /opt/onedev inside the container
      - ${APP_DATA_DIR}/data:/opt/onedev
      # Mounting docker.sock to allow docker management via OneDev
      - /var/run/docker.sock:/var/run/docker.sock
    environment: # Environment variables for configuration
      - hibernate_dialect=io.onedev.server.persistence.PostgreSQLDialect # Specify the Hibernate dialect for PostgreSQL
      - hibernate_connection_driver_class=org.postgresql.Driver # JDBC driver class for PostgreSQL
      - hibernate_connection_url=jdbc:postgresql://big-bear-onedev-db:5432/onedev # JDBC connection URL, pointing to the PostgreSQL service
      - hibernate_connection_username=bigbear # Username for the database connection
      - hibernate_connection_password=eea2dad6-2203-45eb-8908-e8ba4d1e7f92 # Password for the database connection
      - initial_user=bigbear # Initial admin username for OneDev
      - initial_password=password # Initial admin password for OneDev
      - initial_email=admin@example.com # Initial admin email for OneDev
      - initial_server_url=http://localhost:6610 # URL where OneDev will be accessible
    depends_on: # Ensure the database service starts before this service
      - big-bear-onedev-db
    networks: # Connect to the network
      - big_bear_ondedev_network
  # Define the service for the PostgreSQL database
  big-bear-onedev-db:
    image: postgres:14 # Use the specified PostgreSQL image
    restart: unless-stopped # Policy to restart the container unless stopped manually
    environment: # Environment variables for PostgreSQL configuration
      - POSTGRES_USER=bigbear # Default username for PostgreSQL
      - POSTGRES_PASSWORD=eea2dad6-2203-45eb-8908-e8ba4d1e7f92 # Password for the default user
      - POSTGRES_DB=onedev # Default database created upon startup
    volumes: # Mount point for database persistence
      - ${APP_DATA_DIR}/postgres/data:/var/lib/postgresql/data
    networks: # Connect to the network
      - big_bear_ondedev_network
# Define the network for the big-bear-onedev application
networks:
  big_bear_ondedev_network: # Network name
    driver: bridge # Network driver
