# Configuration for ollama-cpu setup
# Name of the big-bear-ollama-cpu application
version: "3.7"
# Service definitions for the big-bear-ollama-cpu application
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-ollama-cpu_big-bear-ollama-cpu_1
      APP_PORT: "11434"
  # Service name: big-bear-ollama-cpu
  # The `big-bear-ollama-cpu` service definition
  big-bear-ollama-cpu:
    # Image to be used for the container
    image: ollama/ollama:0.17.0
    # Container restart policy
    restart: unless-stopped
    # Environment variables
    environment:
      - PORT=11434
    # Volumes to be mounted to the container
    volumes:
      - ${APP_DATA_DIR}/.ollama:/root/.ollama
    devices:
      # Attach GPU
      - /dev/kfd
      - /dev/dri
