# Configuration for big-bear-gotify setup
version: "3.7"
# Service definitions for the big-bear-gotify application
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-gotify_app_1
      APP_PORT: "80"
  # Service name: app
  app:
    image: gotify/server:2.9.0 # Docker image for the service
    environment: # Environment variables for the service
      - GOTIFY_DEFAULTUSER_NAME=admin
      - GOTIFY_DEFAULTUSER_PASS=custom
    volumes: # Volume mapping (host:container)
      - ${APP_DATA_DIR}/data:/app/data
