# Configuration for dozzle setup
# Name of the big-bear-dozzle application
version: "3.7"
# Service definitions for the big-bear-dozzle application
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-dozzle_app_1
      APP_PORT: "8080"
  # Service name: app
  # The `app` service definition
  app:
    # Image to be used for the container
    image: amir20/dozzle:v10.0.6
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      # Mounting docker.sock to allow docker management via the container
      - /var/run/docker.sock:/var/run/docker.sock
