# Configuration for changedetection setup
# Name of the big-bear-changedetection application
version: "3.7"
# Service definitions for the big-bear-changedetection application
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-changedetection_big-bear-changedetection_1
      APP_PORT: "5000"
  # Service name: big-bear-changedetection
  # The `big-bear-changedetection` service definition
  big-bear-changedetection:
    # Image to be used for the container
    image: ghcr.io/dgtlmoon/changedetection.io:0.51.4
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      - ${APP_DATA_DIR}/datastore:/datastore
