# Configuration for big-bear-actual-server setup
version: "3.7"
# Service definitions for the big-bear-actual-server application
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-actual-server_app_1
      APP_PORT: "5006"
  # Service name: app
  app:
    image: actualbudget/actual-server:26.2.0 # The Docker image to use (latest version of actual-server)
    volumes:
      - ${APP_DATA_DIR}/data:/data # Mounting the data volume
    restart: unless-stopped # Policy to restart the container if it stops unexpectedly
