# Configuration for cyberchef setup
# Name of the big-bear-cyberchef application
version: "3.7"
# Service definitions for the big-bear-cyberchef application
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-cyberchef_big-bear-cyberchef_1
      APP_PORT: "80"
  # Service name: big-bear-cyberchef
  # The `big-bear-cyberchef` service definition
  big-bear-cyberchef:
    # Image to be used for the container
    image: ghcr.io/gchq/cyberchef:10.22.0
    # Container restart policy
    restart: unless-stopped
