# Configuration for big-bear-baserow setup
version: "3.7"
# Service definitions for the big-bear-baserow application
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-baserow_app_1
      APP_PORT: "80"
  # Service name: app
  app:
    # Use the specified Docker image for Baserow and specify its version.
    image: baserow/baserow:2.0.6
    # Set environment variables for Baserow.
    environment:
      # Set the your CASA OS IP for Baserow to use.
      BASEROW_PUBLIC_URL: "http://umbrel.local:10009"
    # Define volumes to persist data between container restarts.
    volumes:
      - ${APP_DATA_DIR}/data:/baserow/data
