# Configuration for homer setup
# Name of the big-bear-homer application
version: "3.7"
# Service definitions for the big-bear-homer application
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-homer_app_1
      APP_PORT: "8080"
  # Service name: app
  # The `app` service definition
  app:
    # Specifies the Docker image to be used for the service
    image: b4bz/homer:v25.11.1
    # Binds the container's volumes to host directories or named volumes
    # In this case, bind-mounts `homer_assets` from the host to `/www/assets` inside the container
    volumes:
      - ${APP_DATA_DIR}/assets:/www/assets
    # Specifies the user and group ID under which the container will run
    # The default is user ID 1000 and group ID 1000
    user: 1000:1000 # default
    # Sets environment variables for the container
    # In this case, the `INIT_ASSETS` variable is set to 1 (which is the default value)
    environment:
      - INIT_ASSETS=1 # default
