# Configuration for audiobookshelf setup
# Name of the big-bear-audiobookshelf application
version: "3.7"
# Service definitions for the big-bear-audiobookshelf application
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-audiobookshelf_big-bear-audiobookshelf_1
      APP_PORT: "80"
  # Service name: big-bear-audiobookshelf
  # The `big-bear-audiobookshelf` service definition
  big-bear-audiobookshelf:
    # Image to be used for the container
    image: ghcr.io/advplyr/audiobookshelf:2.32.1
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      - ${APP_DATA_DIR}/media/data/books/spoken:/audiobooks
      - ${APP_DATA_DIR}/media/data/podcasts:/podcasts
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/metadata:/metadata
