# Configuration for komga setup
# Name of the big-bear-komga application
version: "3.7"
# Service definitions for the big-bear-komga application
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-komga_big-bear-komga_1
      APP_PORT: "25600"
  # Service name: big-bear-komga
  # The `big-bear-komga` service definition
  big-bear-komga:
    # Image to be used for the container
    image: ghcr.io/gotson/komga:1.24.1
    # Container restart policy
    restart: unless-stopped
    # Environment variables for the container
    environment:
      - TZ=UTC
    # Volumes to be mounted to the container
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${APP_DATA_DIR}/data:/data
