# Configuration for filebrowser-quantum setup
# Name of the big-bear-filebrowser-quantum application
version: "3.7"
# Service definitions for the big-bear-filebrowser-quantum application
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-filebrowser-quantum_app_1
      APP_PORT: "80"
  # Service name: app
  # The main FileBrowser Quantum application service
  app:
    # Image to be used for the container
    image: gtstef/filebrowser:1.1.3-stable
    # Container restart policy
    restart: unless-stopped
    # Environment variables
    environment:
      - TZ=UTC
    # Volumes to be mounted to the container
    volumes:
      - ${APP_DATA_DIR}/data:/home/filebrowser/data # Database and config
      - ${APP_DATA_DIR}/srv:/srv # Served files
    # Networks for the big-bear-filebrowser-quantum application
    networks:
      - big-bear-filebrowser-quantum-network
# Networks definition for the big-bear-filebrowser-quantum application
networks:
  big-bear-filebrowser-quantum-network:
    driver: bridge
