version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-jlesage-firefox_big-bear-jlesage-firefox_1
      APP_PORT: "5800"
  big-bear-jlesage-firefox:
    image: jlesage/firefox:v26.02.3 # Docker image for the Firefox browser
    environment:
      - VNC_PASSWORD=casaos # Set the VNC password to 'casaos'
      - FF_OPEN_URL=https://community.bigbeartechworld.com/ # Set the default URL to Big Bear Tech World
    volumes:
      - ${APP_DATA_DIR}/config:/config:rw # Mount the host directory to the container's Downloads directory
