# Configuration for wallos setup
# Name of the big-bear-wallos application
version: "3.7"
# Service definitions for the big-bear-wallos application
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-wallos_big-bear-wallos_1
      APP_PORT: "80"
  # Service name: big-bear-wallos
  # The `big-bear-wallos` service definition
  big-bear-wallos:
    # Image to be used for the container
    image: bellamy/wallos:4.6.0
    # Container restart policy
    restart: unless-stopped
    # Environment variables for the container
    environment:
      TZ: "UTC" # Sets the time zone inside the container to Coordinated Universal Time (UTC).
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local /DATA/AppData/big-bear-wallos/db directory to /var/www/html/db inside the container
      - ${APP_DATA_DIR}/db:/var/www/html/db
      # Mounting the local /DATA/AppData/big-bear-wallos/logos directory to /var/www/html/images/uploads/logos inside the container
      - ${APP_DATA_DIR}/logos:/var/www/html/images/uploads/logos
