# Configuration for goaway setup
# Application Name
version: "3.7"
# Services used in the application
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-goaway_big-bear-goaway_1
      APP_PORT: "53"
  # The `big-bear-goaway` service for the goaway application
  big-bear-goaway:
    # Docker image to be used
    image: pommee/goaway:0.62.16
    # Restart policy for the service
    restart: unless-stopped
    # Volumes for the service HOST -> CONTAINER
    volumes:
      - ${APP_DATA_DIR}/config:/app/config
    # Capabilities required for DNS services
    cap_add:
      - NET_BIND_SERVICE
      - NET_RAW
