version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-spoolman_app_1
      APP_PORT: "8000"
  app:
    image: ghcr.io/donkie/spoolman:0.22.1 # Image to use for the spoolman service
    volumes:
      - ${APP_DATA_DIR}/data:/home/app/.local/share/spoolman # Binds a volume from host to container for data storage
    environment:
      - TZ=$TZ # Sets the timezone, using host's timezone variable
      - SPOOLMAN_DB_TYPE=sqlite # Database type (sqlite, mysql, postgres, cockroachdb)
      - SPOOLMAN_LOGGING_LEVEL=INFO # Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
      - SPOOLMAN_AUTOMATIC_BACKUP=TRUE # Enable automatic nightly backups for SQLite
    restart: unless-stopped # Service will restart unless it is explicitly stopped
