# Configuration for big-bear-code-server setup
version: "3.7"
# Service definitions for the big-bear-code-server application
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-code-server_app_1
      APP_PORT: "8443"
  # Service name: app
  app:
    image: linuxserver/code-server:4.106.2 # The Docker image to be used for the service
    environment:
      - PUID=1000 # User ID under which code-server will run
      - PGID=1000 # Group ID under which code-server will run
      - TZ=UTC # Timezone for the container
      - PASSWORD=my_password # Password to access code-server
      - SUDO_PASSWORD=sudo_my_password # Password to access code-server
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - ${APP_DATA_DIR}/config:/config #config dir
      - ${APP_DATA_DIR}/projects:/projects #project dir
    restart: always # Policy to restart the container if it stops unexpectedly
