# Configuration for ollama-amd setup
# Name of the big-bear-ollama-amd application
version: "3.7"
# Service definitions for the big-bear-ollama-amd application
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-ollama-amd_big-bear-ollama-amd_1
      APP_PORT: "11434"
  # Service name: big-bear-ollama-amd
  # The `big-bear-ollama-amd` service definition
  big-bear-ollama-amd:
    # Image to be used for the container
    image: ollama/ollama:0.16.3-rocm
    # Container restart policy
    restart: unless-stopped
    # Environment variables
    environment:
      - PORT=11434
    # Volumes to be mounted to the container
    volumes:
      - ${APP_DATA_DIR}/.ollama:/root/.ollama
    devices:
      # Attach GPU
      - /dev/kfd
      - /dev/dri
