# Configuration for budibase setup
# Name of the big-bear-budibase application
version: "3.7"
# Service definitions for the big-bear-budibase application
services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-budibase_big-bear-budibase_1
      APP_PORT: "80"
  # Service name: big-bear-budibase
  # The `big-bear-budibase` service definition
  big-bear-budibase:
    # Image to be used for the container
    image: budibase/budibase:3.23.30
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local directory ${APP_DATA_DIR}/data to /data in the container
      - ${APP_DATA_DIR}/data:/data
